spring:
  datasource:
    url: jdbc:h2:file:/recruitment_homework/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
